services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: wildfire-protection-backend:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import sys,urllib.request; sys.exit(0 if urllib.request.urlopen('http://localhost:8000/health').getcode()==200 else 1)\""]
      interval: 20s
      timeout: 3s
      retries: 5

networks:
  default:
    name: wildfire-net


